### ISSUE TITLE
iOS/Android example

### ISSUE THREAD

**Issue by RWOverdijk** [salsowelim/dejavu_cpp_port#1]
Hey!

You mention this works on iOS and Android, which is great because I'm in need of something like this. I'd love to help work on it but I'm having trouble getting this to work on iOS. Do you have a small guide or example to help get me started? It'd be great if there were a sandbox of some sort that can create the database and help you get detecting using the microphone of the device.

The biggest issue I face is missing ffmpeg... So maybe an example repository would be nice.

**Comment by salsowelim** [comment]
ffmpeg is used for demo purposes only (i.e run the code in your PC), so it is not required.

Ideally you would have a back-end (server) database that will accept your queries from iOS client (sending the hashes and offsets).

To get this code running on iOS What you should perhaps do is:

 -Add fingerprint.cpp to your xcode project. 

 -Call the function fingerprint(float * data, int data_size) from within your swift or objective-c code, passing the raw recorded audio data.

-Set things up like: including the dependieces (opencv,boost) in xcode, figuring out how to include c++ code in iOS projects (hint: bridging headers?). this is the non-trivial part.

I'm planning in the future to perhaps open source a full mobile client, but It may take some time.

**Comment by RWOverdijk** [comment]
That's all right, thanks for your reply.

I'd ideally not have a backend because of the number of queries I need to do. But I'm closing in on a solution.

Thanks again.
